---

- hosts: pop-os
  become: true
  tasks:
  
  - name: install apache2 package
    apt:
      name: apache2
      state: latest 

  - name: add php support for apache2
    apt:
      name: libapache2-mod-php
      state: latest
